Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
trainer = Trainer(
    state=state,
    composer=composer,
    # logger=LOGGER,
    device=composer.trainer.device,  # type: ignore[arg-type]
)
trainer.remove_callback(event=TrainerEvent.ON_VALID_EPOCH_END.value, callback=save_state)

trainer.add_callback(
    TrainerEvent.ON_VALID_EPOCH_END.value,
    lambda trainer: evaluate_and_generate_on_valid_epoch_end(trainer, num_batches_to_eval=None),
)
_trained_state = trainer.fit(train_loader=train_loader, valid_loader=valid_loader, test_loader=test_loader)
# _trained_state.pretty_print()
history = _trained_state.history
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[59], line 13[0m
[1;32m      7[0m trainer[38;5;241m.[39mremove_callback(event[38;5;241m=[39mTrainerEvent[38;5;241m.[39mON_VALID_EPOCH_END[38;5;241m.[39mvalue, callback[38;5;241m=[39msave_state)
[1;32m      9[0m trainer[38;5;241m.[39madd_callback(
[1;32m     10[0m     TrainerEvent[38;5;241m.[39mON_VALID_EPOCH_END[38;5;241m.[39mvalue,
[1;32m     11[0m     [38;5;28;01mlambda[39;00m trainer: evaluate_and_generate_on_valid_epoch_end(trainer, num_batches_to_eval[38;5;241m=[39m[38;5;28;01mNone[39;00m),
[1;32m     12[0m )
[0;32m---> 13[0m _trained_state [38;5;241m=[39m [43mtrainer[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43mtrain_loader[49m[38;5;241;43m=[39;49m[43mtrain_loader[49m[43m,[49m[43m [49m[43mvalid_loader[49m[38;5;241;43m=[39;49m[43mvalid_loader[49m[43m,[49m[43m [49m[43mtest_loader[49m[38;5;241;43m=[39;49m[43mtest_loader[49m[43m)[49m
[1;32m     14[0m [38;5;66;03m# _trained_state.pretty_print()[39;00m
[1;32m     15[0m history [38;5;241m=[39m _trained_state[38;5;241m.[39mhistory

File [0;32m~/work/omniverse/omniverse/omnivault/transformer/core/trainer.py:458[0m, in [0;36mTrainer.fit[0;34m(self, train_loader, valid_loader, test_loader)[0m
[1;32m    455[0m [38;5;28mself[39m[38;5;241m.[39mtest_loader [38;5;241m=[39m test_loader
[1;32m    457[0m [38;5;66;03m# put callback here because depends on dataloader[39;00m
[0;32m--> 458[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mtrigger_callbacks[49m[43m([49m[43mTrainerEvent[49m[38;5;241;43m.[39;49m[43mON_FIT_START[49m[38;5;241;43m.[39;49m[43mvalue[49m[43m)[49m
[1;32m    460[0m [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m1[39m, [38;5;28mself[39m[38;5;241m.[39mmax_epochs [38;5;241m+[39m [38;5;241m1[39m):
[1;32m    461[0m     [38;5;66;03m# fmt: off[39;00m
[1;32m    462[0m     [38;5;28mself[39m[38;5;241m.[39mepoch_index [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m               [38;5;66;03m# to match range(1, max_epochs + 1) because we start from 1[39;00m

File [0;32m~/work/omniverse/omniverse/omnivault/transformer/core/trainer.py:206[0m, in [0;36mTrainer.trigger_callbacks[0;34m(self, event, *args, **kwargs)[0m
[1;32m    204[0m params [38;5;241m=[39m inspect[38;5;241m.[39msignature(callback)[38;5;241m.[39mparameters
[1;32m    205[0m [38;5;28;01mif[39;00m [38;5;28mall[39m(param [38;5;129;01min[39;00m params [38;5;28;01mfor[39;00m param [38;5;129;01min[39;00m kwargs):
[0;32m--> 206[0m     [43mcallback[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    207[0m [38;5;28;01melse[39;00m:
[1;32m    208[0m     callback([38;5;28mself[39m)

File [0;32m~/work/omniverse/omniverse/omnivault/transformer/core/callbacks.py:72[0m, in [0;36mlog_on_fit_start[0;34m(trainer)[0m
[1;32m     69[0m total_params [38;5;241m=[39m trainer[38;5;241m.[39mmodel[38;5;241m.[39mtotal_parameters
[1;32m     70[0m trainable_params [38;5;241m=[39m trainer[38;5;241m.[39mmodel[38;5;241m.[39mtotal_trainable_parameters
[0;32m---> 72[0m [38;5;28;01massert[39;00m trainer[38;5;241m.[39mcomposer[38;5;241m.[39mmodel [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m MISSING [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(trainer[38;5;241m.[39mcomposer[38;5;241m.[39mmodel, Missing)
[1;32m     73[0m vocab_size [38;5;241m=[39m trainer[38;5;241m.[39mcomposer[38;5;241m.[39mmodel[38;5;241m.[39mvocab_size
[1;32m     74[0m context_length [38;5;241m=[39m trainer[38;5;241m.[39mcomposer[38;5;241m.[39mmodel[38;5;241m.[39mcontext_length

[0;31mAssertionError[0m: 

